name = "ogify-api"
main = "src/index.ts"
compatibility_date = "2024-09-25"
compatibility_flags = ["nodejs_compat"]

[vars]
ENVIRONMENT = "development"
SUPABASE_URL = ""
PADDLE_WEBHOOK_SECRET = ""

[browser]
binding = "BROWSER"
